### ISSUE TITLE
DataSync-1.9.1.jar will not open

### ISSUE THREAD

**Issue by codymays** [socrata/datasync#184]
I am able to run DataSync-1.8.2.jar without an issue (opens successfully) on our Windows 2012 server but when double-clicking to open DataSync-1.9.1.jar or attempting to open from command line nothing happens. We have Java RE 1.7.0_79.

**Comment by rjmac** [comment]
What does it print if you run it from the console with `java -jar DataSync-1.9.1.jar`?

**Comment by codymays** [comment]
Ah, looks like it's a version error.

[image: image.png]

**Comment by rjmac** [comment]
Hm, that image didn't come through, but I'm going to assume it says something like "unsupported major.minor version somethingorother".  Which isn't right, the jar was compiled on java 8 but the build's supposed to be configured to emit java 7 bytecode.  Digging a bit to see what's going on here.

**Comment by codymays** [comment]
Ah, sorry about the image. Here is the exception text:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Socrata\DataSync API>java -jar DataSync-1.9.1.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError:
javax/ws/rs/P
rocessingException : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at
com.socrata.datasync.ui.SimpleIntegrationWizard.getNewIntegrationJob(
SimpleIntegrationWizard.java:431)
        at
com.socrata.datasync.ui.SimpleIntegrationWizard.generateMainPanel(Sim
pleIntegrationWizard.java:628)
        at
com.socrata.datasync.ui.SimpleIntegrationWizard.<init>(SimpleIntegrat
ionWizard.java:138)
        at
com.socrata.datasync.ui.SimpleIntegrationWizard.get(SimpleIntegration
Wizard.java:158)
        at com.socrata.datasync.Main.main(Main.java:32)

**Comment by rjmac** [comment]
Ugh ok I see what's going on.  An included library we upgraded is built for Java 8 now, so even though datasync proper has 1.7 bytecode it still requires 8.  I'm not sure we can downgrade it (the old version of the library was very ancient), but switching to a current version of Java will solve this problem.

**Comment by codymays** [comment]
Gotcha, thanks. So any version 8 and above?

**Comment by rjmac** [comment]
Yep, 8+ should all work.

**Comment by rjmac** [comment]
I've updated the [documentation page](https://socrata.github.com/datasync) to reflect this new minimum verison.
